/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package food_bachelor;

import static com.sun.javafx.scene.control.skin.Utils.getResource;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import meal_count.meal_Project_connection;
import net.proteanit.sql.DbUtils;

public class add_meal extends javax.swing.JFrame {

    Connection conn=null;
    ResultSet rs=null,rr=null;
    PreparedStatement pst=null,p=null;
    Statement st=null;
    
    public add_meal() {
        initComponents();
        conn=meal_Project_connection.ConnecrDb();
        ref();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ughu = new javax.swing.JPanel();
        Addmeal = new javax.swing.JButton();
        m10 = new javax.swing.JTextField();
        m9 = new javax.swing.JTextField();
        m8 = new javax.swing.JTextField();
        m7 = new javax.swing.JTextField();
        m6 = new javax.swing.JTextField();
        m5 = new javax.swing.JTextField();
        m4 = new javax.swing.JTextField();
        m3 = new javax.swing.JTextField();
        m2 = new javax.swing.JTextField();
        m1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        combobox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        refresh_btn = new javax.swing.JButton();
        Datef = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        mm10 = new javax.swing.JTextField();
        mm1 = new javax.swing.JTextField();
        mm6 = new javax.swing.JTextField();
        mm2 = new javax.swing.JTextField();
        mm7 = new javax.swing.JTextField();
        mm3 = new javax.swing.JTextField();
        mm8 = new javax.swing.JTextField();
        mm9 = new javax.swing.JTextField();
        mm4 = new javax.swing.JTextField();
        mm5 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        aa = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        addmoney = new javax.swing.JButton();
        dvvbervbe = new javax.swing.JLabel();
        moneydate = new javax.swing.JTextField();
        mm11 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ughu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Addmeal.setText("Add Meal");
        Addmeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddmealActionPerformed(evt);
            }
        });
        ughu.add(Addmeal, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 390, 170, 40));

        m10.setText("0");
        ughu.add(m10, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 370, 40, -1));

        m9.setText("0");
        ughu.add(m9, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 340, 40, -1));

        m8.setText("0");
        ughu.add(m8, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 310, 40, -1));

        m7.setText("0");
        ughu.add(m7, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 280, 40, -1));

        m6.setText("0");
        ughu.add(m6, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 250, 40, -1));

        m5.setText("0");
        ughu.add(m5, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 220, 40, -1));

        m4.setText("0");
        ughu.add(m4, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 190, 40, -1));

        m3.setText("0");
        ughu.add(m3, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 160, 40, -1));

        m2.setText("0");
        ughu.add(m2, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 130, 40, -1));

        m1.setText("0");
        ughu.add(m1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 100, 40, -1));

        jLabel1.setText("M10");
        ughu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 370, -1, -1));

        jLabel2.setText("M9");
        ughu.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 340, -1, -1));

        jLabel3.setText("M8");
        ughu.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 310, -1, -1));

        jLabel4.setText("M7");
        ughu.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 280, -1, -1));

        jLabel5.setText("M6");
        ughu.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 250, -1, -1));

        jLabel6.setText("M5");
        ughu.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 220, -1, -1));

        jLabel7.setText("M4");
        ughu.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 190, -1, -1));

        jLabel8.setText("M3");
        ughu.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 160, -1, -1));

        jLabel9.setText("M2");
        ughu.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 130, -1, -1));

        jLabel10.setText("M1");
        ughu.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 100, -1, -1));

        combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select an item" }));
        combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxActionPerformed(evt);
            }
        });
        ughu.add(combobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 0, 170, 40));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        ughu.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 430));

        refresh_btn.setText("Refresh");
        refresh_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh_btnActionPerformed(evt);
            }
        });
        ughu.add(refresh_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 110, 40));
        ughu.add(Datef, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 60, 80, 30));

        jLabel11.setText("Date");
        ughu.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 40, -1, -1));

        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        ughu.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 90, 110));

        jButton2.setText("Setting");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        ughu.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 110, 40));

        jButton3.setText("Home");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        ughu.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 510, 110, 40));

        jLabel13.setText("Jerry");
        ughu.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 160, -1, -1));

        jLabel14.setText("Aunshon");
        ughu.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 100, -1, -1));

        jLabel15.setText("parvez");
        ughu.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 130, -1, -1));

        jLabel16.setText("kajol");
        ughu.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 190, -1, -1));

        jLabel17.setText("sojib");
        ughu.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 220, -1, -1));

        jLabel18.setText("robin");
        ughu.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 250, -1, -1));

        jLabel19.setText("Vai");
        ughu.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 280, -1, -1));

        jButton5.setText("count Page");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        ughu.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 510, 110, 40));

        mm10.setText("0");
        ughu.add(mm10, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 530, 90, 30));

        mm1.setText("0");
        ughu.add(mm1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 470, 90, 30));

        mm6.setText("0");
        ughu.add(mm6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 530, 90, 30));

        mm2.setText("0");
        ughu.add(mm2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 470, 90, 30));

        mm7.setText("0");
        ughu.add(mm7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 530, 90, 30));

        mm3.setText("0");
        ughu.add(mm3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 470, 90, 30));

        mm8.setText("0");
        ughu.add(mm8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 530, 90, 30));

        mm9.setText("0");
        ughu.add(mm9, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 530, 90, 30));

        mm4.setText("0");
        ughu.add(mm4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 470, 90, 30));

        mm5.setText("0");
        ughu.add(mm5, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 470, 90, 30));

        jLabel25.setText("Aunshon");
        ughu.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 450, -1, -1));

        jLabel26.setText("Robin");
        ughu.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 510, -1, -1));

        jLabel27.setText("Parvez");
        ughu.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 450, -1, -1));

        jLabel28.setText("Jerry");
        ughu.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 450, -1, -1));

        jLabel29.setText("Kajol");
        ughu.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 450, -1, -1));

        jLabel30.setText("M9");
        ughu.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 510, -1, -1));

        jLabel31.setText("M10");
        ughu.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 510, -1, -1));

        jLabel32.setText("Sojib");
        ughu.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 450, -1, -1));

        jLabel33.setText("M8");
        ughu.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 510, -1, -1));

        jLabel34.setText("Vai");
        ughu.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 510, -1, -1));
        ughu.add(aa, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 440, 0, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Add Money");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(280, 0, 70, 15);

        addmoney.setText("Add");
        addmoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addmoneyActionPerformed(evt);
            }
        });
        jPanel1.add(addmoney);
        addmoney.setBounds(630, 40, 110, 90);

        dvvbervbe.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        dvvbervbe.setText("Money Entry Date");
        jPanel1.add(dvvbervbe);
        dvvbervbe.setBounds(520, 20, 110, 20);

        moneydate.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel1.add(moneydate);
        moneydate.setBounds(520, 40, 100, 30);

        mm11.setText("0");
        jPanel1.add(mm11);
        mm11.setBounds(520, 100, 100, 30);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel20.setText("Today's Spend");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(530, 80, 90, 14);

        ughu.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, 750, 140));

        getContentPane().add(ughu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void ref(){
        //combobox.setSelectedItem(null);
        try{
					ResultSet rs = null;
				    DatabaseMetaData meta = conn.getMetaData();
				    rs = meta.getTables(null, null, null, new String[]{"TABLE"});

				    while (rs.next()) {
				      String tableName = rs.getString("TABLE_NAME");
				      //System.out.println("tableName=" + tableName);
                                      
                                      
                                          combobox.addItem(tableName);
                                      
				      
				      
				    }

					
				}catch(Exception e){
					JOptionPane.showMessageDialog(null,e.getMessage());
				}
    }
    
    public void newref(){
        try{
            String query="select * from "+combobox.getSelectedItem()+" ";//from members_and_meals
            PreparedStatement pst = conn.prepareStatement(query);
            ResultSet rs = pst.executeQuery();

            table.setModel(DbUtils.resultSetToTableModel(rs));

            pst.close();
            rs.close();

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);

        }
        
        /*try{
           String query="select sum(Aunshon) from "+combobox.getSelectedItem()+" ";
           PreparedStatement pst = conn.prepareStatement(query);
					
					ResultSet rs = pst.executeQuery();
                                        while(rs.next())
					{
                                                String sum=rs.getString("sum(Aunshon)");
                                                a.setText(sum);
						
                                                
					}
                                        //JOptionPane.showMessageDialog(null, "YES");
					pst.close();
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, e.getMessage());
       }*/
        
    }
    private void AddmealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddmealActionPerformed
        try
	   {
               String u=Datef.getText().toString();
		if(u.isEmpty()){
                    JOptionPane.showMessageDialog(null, "Date is empty");
                }
                else{
                    String query = " insert into "+combobox.getSelectedItem()+" (Date,Aunshon,Parvez,Jerry,Kajol,Sojib,Robin,Vai,m8,m9,m10) values (?,?,?,?,?,?,?,?,?,?,?)";
	PreparedStatement pst = conn.prepareStatement(query);
		
        
        pst.setString(1,Datef.getText());
	pst.setString(2,m1.getText());				
	pst.setString(3,m2.getText());
	pst.setString(4,m3.getText());
	pst.setString(5,m4.getText());
	pst.setString(6,m5.getText());
        pst.setString(7,m6.getText());
        pst.setString(8,m7.getText());
        pst.setString(9,m8.getText());
        pst.setString(10,m9.getText());
        pst.setString(11,m10.getText());
	pst.execute();
	pst.close();
        Datef.setText("");m1.setText("0");mm11.setText("0");m2.setText("0");m3.setText("0");m4.setText("0");m5.setText("0");m6.setText("0");m7.setText("0");m8.setText("0");m9.setText("0");m10.setText("0");
	//JOptionPane.showMessageDialog(null, "Meal Added added");
        //new add_meal().setVisible(true);
       // dispose();
       newref();
                }
					
	    
			
	} catch (Exception es) {
		//JOptionPane.showMessageDialog(null, es.getMessage());
                JOptionPane.showMessageDialog(null, "please select month  ! this is money list . \nyou can not add meal in the money list");
	}
    }//GEN-LAST:event_AddmealActionPerformed

    private void comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxActionPerformed

        try{
            String test=combobox.getSelectedItem().toString();
            if(test=="Select an item"){
               // table.setModel();
                //Datef.setText("");m1.setText("0");m2.setText("0");m3.setText("0");m4.setText("0");m5.setText("0");m6.setText("0");m7.setText("0");m8.setText("0");m9.setText("0");m10.setText("0");
            new add_meal().setVisible(true);
            dispose();
            }
            else{
                String query="select * from "+combobox.getSelectedItem()+" ";//from members_and_meals
            PreparedStatement pst = conn.prepareStatement(query);
            ResultSet rs = pst.executeQuery();

            table.setModel(DbUtils.resultSetToTableModel(rs));

            pst.close();
            rs.close();

            newref();
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);

        }

    }//GEN-LAST:event_comboboxActionPerformed

    private void refresh_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh_btnActionPerformed
        new add_meal().setVisible(true);
        dispose();

    }//GEN-LAST:event_refresh_btnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new member_and_meal_list().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
         try{
					int row = table.getSelectedRow();
					String Serial_=(table.getModel().getValueAt(row, 0)).toString();
					
					String query = "select * from "+combobox.getSelectedItem()+" where Date='"+Serial_+"'";
					PreparedStatement pst = conn.prepareStatement(query);
					
					ResultSet rs = pst.executeQuery();
					
					
					while(rs.next())
					{
                                                Datef.setText(rs.getString("Date"));
						m1.setText(rs.getString("Aunshon"));
						m2.setText(rs.getString("Parvez"));
						m3.setText(rs.getString("Jerry"));
						m4.setText(rs.getString("Kajol"));
                                                m5.setText(rs.getString("Sojib"));
                                                m6.setText(rs.getString("Robin"));
                                                m7.setText(rs.getString("Vai"));
                                                m8.setText(rs.getString("M8"));
                                                m9.setText(rs.getString("M9"));
                                                m10.setText(rs.getString("M10"));
                                                
					}
                                        //JOptionPane.showMessageDialog(null, "YES");
					pst.close();
				}	
	
				catch (Exception ef){
				JOptionPane.showMessageDialog(null, ef.getMessage());
				}
    }//GEN-LAST:event_tableMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new countpage().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new Home().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void addmoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addmoneyActionPerformed
        try
	   {
               if(moneydate.getText().toString().isEmpty()){
                   JOptionPane.showMessageDialog(null,"You have to fill the money entry date");
               }
               else{
                          
        String query = " insert into money_of_"+combobox.getSelectedItem()+" (mdate,mAunshon,mParvez,mJerry,mKajol,mSojib,mRobin,mVai,mM8,mM9,mM10,mSpend) values (?,?,?,?,?,?,?,?,?,?,?,?)";
	PreparedStatement pst = conn.prepareStatement(query);
		
        
        pst.setString(1,moneydate.getText());
	pst.setString(2,mm1.getText());				
	pst.setString(3,mm2.getText());
	pst.setString(4,mm3.getText());
	pst.setString(5,mm4.getText());
	pst.setString(6,mm5.getText());
        pst.setString(7,mm6.getText());
        pst.setString(8,mm7.getText());
        pst.setString(9,mm8.getText());
        pst.setString(10,mm9.getText());
        pst.setString(11,mm10.getText());
        pst.setString(12,mm11.getText());
	pst.execute();
	pst.close();
        Datef.setText("");mm11.setText("0");m2.setText("0");m3.setText("0");m4.setText("0");m5.setText("0");m6.setText("0");m7.setText("0");m8.setText("0");m9.setText("0");m10.setText("0");
        moneydate.setText("");mm1.setText("0");mm2.setText("0");mm3.setText("0");mm4.setText("0");mm5.setText("0");mm6.setText("0");mm7.setText("0");mm8.setText("0");mm9.setText("0");mm10.setText("0");	
        JOptionPane.showMessageDialog(null, "Money added");
        //new add_meal().setVisible(true);
       // dispose();
       newref();
                
					
	   
               }
         
			
	} catch (Exception es) {
		//JOptionPane.showMessageDialog(null, es.getMessage());
                JOptionPane.showMessageDialog(null, "please select month  ! this is money list . \nyou can not add money directly to the money list");
	}
    }//GEN-LAST:event_addmoneyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add_meal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add_meal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add_meal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add_meal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new add_meal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addmeal;
    private javax.swing.JTextField Datef;
    private javax.swing.JLabel aa;
    private javax.swing.JButton addmoney;
    private javax.swing.JComboBox<String> combobox;
    private javax.swing.JLabel dvvbervbe;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField m1;
    private javax.swing.JTextField m10;
    private javax.swing.JTextField m2;
    private javax.swing.JTextField m3;
    private javax.swing.JTextField m4;
    private javax.swing.JTextField m5;
    private javax.swing.JTextField m6;
    private javax.swing.JTextField m7;
    private javax.swing.JTextField m8;
    private javax.swing.JTextField m9;
    private javax.swing.JTextField mm1;
    private javax.swing.JTextField mm10;
    private javax.swing.JTextField mm11;
    private javax.swing.JTextField mm2;
    private javax.swing.JTextField mm3;
    private javax.swing.JTextField mm4;
    private javax.swing.JTextField mm5;
    private javax.swing.JTextField mm6;
    private javax.swing.JTextField mm7;
    private javax.swing.JTextField mm8;
    private javax.swing.JTextField mm9;
    private javax.swing.JTextField moneydate;
    private javax.swing.JButton refresh_btn;
    private javax.swing.JTable table;
    private javax.swing.JPanel ughu;
    // End of variables declaration//GEN-END:variables

    
}
