/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package food_bachelor;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import meal_count.meal_Project_connection;
import net.proteanit.sql.DbUtils;
public class countpage extends javax.swing.JFrame {

     Connection conn=null;
    ResultSet rs=null,rr=null;
    PreparedStatement pst=null,p=null;
    public countpage() {
        initComponents();
        conn=meal_Project_connection.ConnecrDb();
        ref();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        combobox = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        a = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        b = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        c = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        d = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        e = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        f = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        g = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        h = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        i = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        j = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        totalf = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        totalf1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        j1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        i1 = new javax.swing.JTextField();
        h1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        g1 = new javax.swing.JTextField();
        f1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        e1 = new javax.swing.JTextField();
        d1 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        c1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        b1 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        a1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        ml = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        msp = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        a2 = new javax.swing.JTextField();
        b2 = new javax.swing.JTextField();
        b3 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        c2 = new javax.swing.JTextField();
        c3 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        d2 = new javax.swing.JTextField();
        d3 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        e2 = new javax.swing.JTextField();
        e3 = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        f2 = new javax.swing.JTextField();
        f3 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        g2 = new javax.swing.JTextField();
        g3 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        h2 = new javax.swing.JTextField();
        h3 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        i2 = new javax.swing.JTextField();
        i3 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        j2 = new javax.swing.JTextField();
        j3 = new javax.swing.JTextField();
        a3 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel46 = new javax.swing.JLabel();
        ex = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 370));

        combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select an item" }));
        combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxActionPerformed(evt);
            }
        });
        jPanel1.add(combobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, 170, 30));

        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 610, 140, 20));

        jButton3.setText("Home");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 580, 140, 20));

        jButton2.setText("Setting");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 550, 140, 20));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel2.setLayout(null);
        jPanel2.add(a);
        a.setBounds(10, 50, 50, 40);

        jLabel1.setText("Aunshon");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 30, 60, 14);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Meal DeshBoard");
        jLabel2.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel2.add(jLabel2);
        jLabel2.setBounds(310, 10, 110, 14);

        jLabel3.setText("Parvez");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(80, 30, 50, 14);
        jPanel2.add(b);
        b.setBounds(70, 50, 50, 40);

        jLabel4.setText("Jerry");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(130, 30, 50, 14);
        jPanel2.add(c);
        c.setBounds(130, 50, 50, 40);

        jLabel5.setText("Kajol");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(190, 30, 50, 14);
        jPanel2.add(d);
        d.setBounds(190, 50, 50, 40);

        jLabel6.setText("Sojib");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(250, 30, 50, 14);
        jPanel2.add(e);
        e.setBounds(250, 50, 50, 40);

        jLabel7.setText("Robin");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(310, 30, 50, 14);
        jPanel2.add(f);
        f.setBounds(310, 50, 50, 40);

        jLabel8.setText("Vai");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(390, 30, 20, 14);
        jPanel2.add(g);
        g.setBounds(370, 50, 50, 40);

        jLabel9.setText("M8");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(460, 30, 20, 14);
        jPanel2.add(h);
        h.setBounds(430, 50, 50, 40);

        jLabel10.setText("M9");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(514, 30, 20, 14);
        jPanel2.add(i);
        i.setBounds(490, 50, 50, 40);

        jLabel11.setText("M10");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(570, 30, 30, 14);
        jPanel2.add(j);
        j.setBounds(550, 50, 50, 40);

        jLabel12.setText("Total Meal");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(650, 30, 60, 14);
        jPanel2.add(totalf);
        totalf.setBounds(630, 50, 100, 40);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("=");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(610, 50, 20, 22);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 740, 120));

        jButton4.setText("Add Meal");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 520, 140, 20));

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel4.setLayout(null);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Total Money");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(860, 30, 90, 14);

        totalf1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel4.add(totalf1);
        totalf1.setBounds(840, 50, 100, 30);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("=");
        jPanel4.add(jLabel15);
        jLabel15.setBounds(810, 50, 20, 22);
        jPanel4.add(j1);
        j1.setBounds(730, 50, 70, 30);

        jLabel16.setText("M10");
        jPanel4.add(jLabel16);
        jLabel16.setBounds(750, 30, 30, 14);

        jLabel17.setText("M9");
        jPanel4.add(jLabel17);
        jLabel17.setBounds(670, 30, 20, 14);
        jPanel4.add(i1);
        i1.setBounds(650, 50, 70, 30);
        jPanel4.add(h1);
        h1.setBounds(570, 50, 70, 30);

        jLabel18.setText("M8");
        jPanel4.add(jLabel18);
        jLabel18.setBounds(600, 30, 20, 14);

        jLabel19.setText("Vai");
        jPanel4.add(jLabel19);
        jLabel19.setBounds(510, 30, 20, 14);
        jPanel4.add(g1);
        g1.setBounds(490, 50, 70, 30);
        jPanel4.add(f1);
        f1.setBounds(410, 50, 70, 30);

        jLabel20.setText("Robin");
        jPanel4.add(jLabel20);
        jLabel20.setBounds(420, 30, 50, 14);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setText("Money DeshBoard");
        jLabel21.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel4.add(jLabel21);
        jLabel21.setBounds(430, 10, 110, 14);

        jLabel22.setText("Sojib");
        jPanel4.add(jLabel22);
        jLabel22.setBounds(350, 30, 50, 14);
        jPanel4.add(e1);
        e1.setBounds(330, 50, 70, 30);
        jPanel4.add(d1);
        d1.setBounds(250, 50, 70, 30);

        jLabel23.setText("Kajol");
        jPanel4.add(jLabel23);
        jLabel23.setBounds(270, 30, 50, 14);
        jPanel4.add(c1);
        c1.setBounds(170, 50, 70, 30);

        jLabel24.setText("Jerry");
        jPanel4.add(jLabel24);
        jLabel24.setBounds(190, 30, 50, 14);
        jPanel4.add(b1);
        b1.setBounds(90, 50, 70, 30);

        jLabel25.setText("Parvez");
        jPanel4.add(jLabel25);
        jLabel25.setBounds(110, 30, 50, 14);

        jLabel26.setText("Aunshon");
        jPanel4.add(jLabel26);
        jLabel26.setBounds(20, 30, 60, 14);
        jPanel4.add(a1);
        a1.setBounds(10, 50, 70, 30);

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 950, 120));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 51), 2));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel27.setText("Meal Rate");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        ml.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel3.add(ml, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 90, 60));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 380, 90, 100));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 51), 2));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel28.setText("Total Money");
        jLabel28.setToolTipText("");
        jPanel5.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        msp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel5.add(msp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 90, 60));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel29.setText("Spend");
        jPanel5.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 380, 90, 100));

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel30.setText("Eaten");
        jPanel6.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel31.setText("Due");
        jPanel6.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        jLabel32.setText("Aunshon");
        jPanel6.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        jLabel33.setText("Parvez");
        jPanel6.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));
        jPanel6.add(a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 80, -1));
        jPanel6.add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 80, -1));

        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        jPanel6.add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 80, -1));

        jLabel34.setText("Jerry");
        jPanel6.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));
        jPanel6.add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 80, -1));

        c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3ActionPerformed(evt);
            }
        });
        jPanel6.add(c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 80, -1));

        jLabel35.setText("Kajol");
        jPanel6.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));
        jPanel6.add(d2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 80, -1));
        jPanel6.add(d3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 80, -1));

        jLabel36.setText("Sojib");
        jPanel6.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));
        jPanel6.add(e2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 80, -1));
        jPanel6.add(e3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 80, -1));

        jLabel37.setText("Robin");
        jPanel6.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));
        jPanel6.add(f2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 80, -1));
        jPanel6.add(f3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 80, -1));

        jLabel38.setText("Vai");
        jPanel6.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));
        jPanel6.add(g2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 80, -1));
        jPanel6.add(g3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 80, -1));

        jLabel39.setText("M8");
        jPanel6.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));
        jPanel6.add(h2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 80, -1));
        jPanel6.add(h3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 80, -1));

        jLabel40.setText("M9");
        jPanel6.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, -1));
        jPanel6.add(i2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 80, -1));
        jPanel6.add(i3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 80, -1));

        jLabel41.setText("M10");
        jPanel6.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, -1, -1));
        jPanel6.add(j2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 80, -1));
        jPanel6.add(j3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 80, -1));
        jPanel6.add(a3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 80, -1));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 30, 170, 420));

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel46.setText("Extra Money");
        jPanel7.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, -1, -1));

        ex.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jPanel7.add(ex, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 150, -1));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 460, 170, 50));

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

     public void ref(){
        //combobox.setSelectedItem(null);
        try{
					ResultSet rs = null;
				    DatabaseMetaData meta = conn.getMetaData();
				    rs = meta.getTables(null, null, null, new String[]{"TABLE"});

				    while (rs.next()) {
				      String tableName = rs.getString("TABLE_NAME");
				      //System.out.println("tableName=" + tableName);
				      combobox.addItem(tableName);
				      
				    }

					
				}catch(Exception e){
					JOptionPane.showMessageDialog(null,e.getMessage());
				}
    }
     public void newref(){
        try{
            String query="select Date,Aunshon,Parvez,Jerry,Kajol,Sojib,Robin,Vai,M8 ,M9 ,M10  from "+combobox.getSelectedItem()+" ";
            //String query="select * from "+combobox.getSelectedItem()+" ";//from members_and_meals
            PreparedStatement pst = conn.prepareStatement(query);
            ResultSet rs = pst.executeQuery();

            table.setModel(DbUtils.resultSetToTableModel(rs));

            pst.close();
            rs.close();

        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);

        }
        
        try{
           String query="select sum(Aunshon),sum(Parvez),sum(Jerry),sum(Kajol),sum(Sojib),Sum(Robin),sum(Vai),sum(M8) ,sum(M9) ,sum(M10)  from "+combobox.getSelectedItem()+" ";
           PreparedStatement pst = conn.prepareStatement(query);
					
					ResultSet rs = pst.executeQuery();
                                        while(rs.next())
					{
                                                String asum=rs.getString("sum(Aunshon)");
                                                a.setText(asum);
                                                double sa=Double.parseDouble(asum);
                                                
                                                String bsum=rs.getString("sum(Parvez)");
                                                b.setText(bsum);
                                                double sb=Double.parseDouble(bsum);
                                                
                                                String csum=rs.getString("sum(Jerry)");
                                                c.setText(csum);
                                                double sc=Double.parseDouble(csum);
                                                
                                                String dsum=rs.getString("sum(Kajol)");
                                                d.setText(dsum);
                                                double sd=Double.parseDouble(dsum);
                                                
                                                String esum=rs.getString("sum(Sojib)");
                                                e.setText(esum);
                                                double se=Double.parseDouble(esum);
                                                
                                                String fsum=rs.getString("sum(Robin)");
                                                f.setText(fsum);
                                                double sf=Double.parseDouble(fsum);
                                                
                                                String gsum=rs.getString("sum(Vai)");
                                                g.setText(gsum);
                                                double sg=Double.parseDouble(gsum);
                                                
                                                String hsum=rs.getString("sum(M8)");
                                                h.setText(hsum);
                                                double sh=Double.parseDouble(hsum);
                                                
                                                String isum=rs.getString("sum(M9)");
                                                i.setText(isum);
                                                double si=Double.parseDouble(isum);
                                                
                                                String jsum=rs.getString("sum(M10)");
                                                j.setText(jsum);
                                                double sj=Double.parseDouble(jsum);
						
                                                double total=sa+sb+sc+sd+se+sf+sg+sh+si+sj;
                                                totalf.setText(Double.toString(total));
					}
                                        //JOptionPane.showMessageDialog(null, "YES");
					pst.close();
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, e.getMessage());
       }
        try{
           String query="select sum(mAunshon),sum(mParvez),sum(mJerry),sum(mKajol),sum(mSojib),Sum(mRobin),sum(mVai),sum(mM8) ,sum(mM9) ,sum(mM10),sum(mSpend)  from money_of_"+combobox.getSelectedItem()+" ";
           PreparedStatement pst = conn.prepareStatement(query);
					
					ResultSet rs = pst.executeQuery();
                                        while(rs.next())
					{
                                                String asum=rs.getString("sum(mAunshon)");
                                                a1.setText(asum);
                                                double sa=Double.parseDouble(asum);
                                                
                                                String bsum=rs.getString("sum(mParvez)");
                                                b1.setText(bsum);
                                                double sb=Double.parseDouble(bsum);
                                                
                                                String csum=rs.getString("sum(mJerry)");
                                                c1.setText(csum);
                                                double sc=Double.parseDouble(csum);
                                                
                                                String dsum=rs.getString("sum(mKajol)");
                                                d1.setText(dsum);
                                                double sd=Double.parseDouble(dsum);
                                                
                                                String esum=rs.getString("sum(mSojib)");
                                                e1.setText(esum);
                                                double se=Double.parseDouble(esum);
                                                
                                                String fsum=rs.getString("sum(mRobin)");
                                                f1.setText(fsum);
                                                double sf=Double.parseDouble(fsum);
                                                
                                                String gsum=rs.getString("sum(mVai)");
                                                g1.setText(gsum);
                                                double sg=Double.parseDouble(gsum);
                                                
                                                String hsum=rs.getString("sum(mM8)");
                                                h1.setText(hsum);
                                                double sh=Double.parseDouble(hsum);
                                                
                                                String isum=rs.getString("sum(mM9)");
                                                i1.setText(isum);
                                                double si=Double.parseDouble(isum);
                                                
                                                String jsum=rs.getString("sum(mM10)");
                                                j1.setText(jsum);
                                                double sj=Double.parseDouble(jsum);
						
                                                double total=sa+sb+sc+sd+se+sf+sg+sh+si+sj;
                                                totalf1.setText(Double.toString(total));
                                                
                                                String sp=rs.getString("sum(mSpend)");
                                                msp.setText(sp);
                                               // double sj=Double.parseDouble(jsum);
					}
                                        //JOptionPane.showMessageDialog(null, "YES");
					pst.close();
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, e.getMessage());
       }
        
        double allmeal=Double.parseDouble(totalf.getText());
        double moneyspend=Double.parseDouble(msp.getText());
        double allmoney=Double.parseDouble(totalf1.getText());
        double extra=allmoney-moneyspend;
        
        ex.setText(Double.toString(extra));
        
        double meal_rate=moneyspend/allmeal;
         System.out.println(meal_rate);
        DecimalFormat Decimal=new DecimalFormat("####.####");
        String output=Decimal.format(meal_rate);
        ml.setText(output);
        
        DecimalFormat decimal=new DecimalFormat("####.###");
        
        double ea=Double.parseDouble(a.getText());
        double aeaten=ea*meal_rate;
        String aoutput=decimal.format(aeaten);
        a2.setText(aoutput);
        double ataka=Double.parseDouble(a1.getText());
        double adue=ataka-aeaten;
        String at=decimal.format(adue);
        a3.setText(at);
       
        double eb=Double.parseDouble(b.getText());
        double beaten=eb*meal_rate;
        String boutput=decimal.format(beaten);
        b2.setText(boutput);
        double btaka=Double.parseDouble(b1.getText());
        double bdue=btaka-beaten;
        String bt=decimal.format(bdue);
        b3.setText(bt);
        
        double cea=Double.parseDouble(c.getText());
        double ceaten=cea*meal_rate;
        String coutput=decimal.format(ceaten);
        c2.setText(coutput);
        double ctaka=Double.parseDouble(c1.getText());
        double cdue=ctaka-ceaten;
        String ct=decimal.format(cdue);
        c3.setText(ct);
        
        double eea=Double.parseDouble(e.getText());
        double eeaten=eea*meal_rate;
        String eoutput=decimal.format(eeaten);
        e2.setText(eoutput);
        double etaka=Double.parseDouble(e1.getText());
        double edue=etaka-eeaten;
        String et=decimal.format(edue);
        e3.setText(et);
        
        double dea=Double.parseDouble(d.getText());
        double deaten=dea*meal_rate;
        String doutput=decimal.format(deaten);
        d2.setText(doutput);
        double dtaka=Double.parseDouble(d1.getText());
        double ddue=dtaka-deaten;
        String dt=decimal.format(ddue);
        d3.setText(dt);
        
        double fea=Double.parseDouble(f.getText());
        double featen=fea*meal_rate;
        String foutput=decimal.format(featen);
        f2.setText(foutput);
        double ftaka=Double.parseDouble(f1.getText());
        double fdue=ftaka-featen;
        String ft=decimal.format(fdue);
        f3.setText(ft);
        
        double gea=Double.parseDouble(g.getText());
        double geaten=gea*meal_rate;
        String goutput=decimal.format(geaten);
        g2.setText(goutput);
        double gtaka=Double.parseDouble(g1.getText());
        double gdue=gtaka-geaten;
        String gt=decimal.format(gdue);
        g3.setText(gt);
        
        double hea=Double.parseDouble(h.getText());
        double heaten=hea*meal_rate;
        String houtput=decimal.format(heaten);
        h2.setText(houtput);
        double htaka=Double.parseDouble(h1.getText());
        double hdue=htaka-heaten;
        String ht=decimal.format(hdue);
        h3.setText(ht);
        
        double iea=Double.parseDouble(i.getText());
        double ieaten=iea*meal_rate;
        String ioutput=decimal.format(ieaten);
        i2.setText(ioutput);
        double itaka=Double.parseDouble(i1.getText());
        double idue=itaka-ieaten;
        String it=decimal.format(idue);
        i3.setText(it);
        
        double jea=Double.parseDouble(j.getText());
        double jeaten=jea*meal_rate;
        String joutput=decimal.format(jeaten);
        j2.setText(joutput);
        double jtaka=Double.parseDouble(j1.getText());
        double jdue=jtaka-jeaten;
        String jt=decimal.format(jdue);
        j3.setText(jt);
        
        
    }
    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        
    }//GEN-LAST:event_tableMouseClicked

    private void comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxActionPerformed

        try{
            String test=combobox.getSelectedItem().toString();
            if(test=="Select an item"){
               // table.setModel();
                //Datef.setText("");m1.setText("0");m2.setText("0");m3.setText("0");m4.setText("0");m5.setText("0");m6.setText("0");m7.setText("0");m8.setText("0");m9.setText("0");m10.setText("0");
            new countpage().setVisible(true);
            dispose();
            }
            else{
                String query="select * from "+combobox.getSelectedItem()+" ";//from members_and_meals
            PreparedStatement pst = conn.prepareStatement(query);
            ResultSet rs = pst.executeQuery();

            table.setModel(DbUtils.resultSetToTableModel(rs));

            pst.close();
            rs.close();
            newref();
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_comboboxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new member_and_meal_list().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        new add_meal().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       new Home().setVisible(true);
       dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b3ActionPerformed

    private void c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(countpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(countpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(countpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(countpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new countpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a;
    private javax.swing.JTextField a1;
    private javax.swing.JTextField a2;
    private javax.swing.JTextField a3;
    private javax.swing.JTextField b;
    private javax.swing.JTextField b1;
    private javax.swing.JTextField b2;
    private javax.swing.JTextField b3;
    private javax.swing.JTextField c;
    private javax.swing.JTextField c1;
    private javax.swing.JTextField c2;
    private javax.swing.JTextField c3;
    private javax.swing.JComboBox<String> combobox;
    private javax.swing.JTextField d;
    private javax.swing.JTextField d1;
    private javax.swing.JTextField d2;
    private javax.swing.JTextField d3;
    private javax.swing.JTextField e;
    private javax.swing.JTextField e1;
    private javax.swing.JTextField e2;
    private javax.swing.JTextField e3;
    private javax.swing.JTextField ex;
    private javax.swing.JTextField f;
    private javax.swing.JTextField f1;
    private javax.swing.JTextField f2;
    private javax.swing.JTextField f3;
    private javax.swing.JTextField g;
    private javax.swing.JTextField g1;
    private javax.swing.JTextField g2;
    private javax.swing.JTextField g3;
    private javax.swing.JTextField h;
    private javax.swing.JTextField h1;
    private javax.swing.JTextField h2;
    private javax.swing.JTextField h3;
    private javax.swing.JTextField i;
    private javax.swing.JTextField i1;
    private javax.swing.JTextField i2;
    private javax.swing.JTextField i3;
    private javax.swing.JTextField j;
    private javax.swing.JTextField j1;
    private javax.swing.JTextField j2;
    private javax.swing.JTextField j3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField ml;
    private javax.swing.JTextField msp;
    private javax.swing.JTable table;
    private javax.swing.JTextField totalf;
    private javax.swing.JTextField totalf1;
    // End of variables declaration//GEN-END:variables
}
