/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package food_bachelor;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import meal_count.meal_Project_connection;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Aunshon
 */
public class member_and_meal_list extends javax.swing.JFrame {

    Connection conn=null;
    ResultSet rs=null,rr=null;
    PreparedStatement pst=null,p=null;
    public member_and_meal_list() {
        initComponents();
        conn=meal_Project_connection.ConnecrDb();
        ref();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        Home = new javax.swing.JButton();
        refresh_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        combobox = new javax.swing.JComboBox<>();
        delete_month = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setText("Change Selected Month Name");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 200, 40));

        Home.setText("Home");
        jPanel1.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 30, 120, 40));

        refresh_btn.setText("Refresh");
        refresh_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh_btnActionPerformed(evt);
            }
        });
        jPanel1.add(refresh_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 30, 120, 40));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 950, -1));

        combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select an item" }));
        combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxActionPerformed(evt);
            }
        });
        jPanel1.add(combobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 150, 40));

        delete_month.setText("Delete Selected Month");
        delete_month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_monthActionPerformed(evt);
            }
        });
        jPanel1.add(delete_month, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 160, 40));

        jButton2.setText("Add new Month");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 150, 40));

        jButton1.setText("Add Meal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 140, 40));

        jButton4.setText("Exit");
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 490, 140, 40));

        jButton5.setText("Count Page");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, 100, 40));

        jButton6.setText("Home");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 493, 90, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void ref(){
        //combobox.setSelectedItem(null);
        try{
					ResultSet rs = null;
				    DatabaseMetaData meta = conn.getMetaData();
				    rs = meta.getTables(null, null, null, new String[]{"TABLE"});

				    while (rs.next()) {
				      String tableName = rs.getString("TABLE_NAME");
				      //System.out.println("tableName=" + tableName);
				      combobox.addItem(tableName);
				      
				    }

					
				}catch(Exception e){
					JOptionPane.showMessageDialog(null,e.getMessage());
				}
    }
    
    private void refresh_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh_btnActionPerformed
        new member_and_meal_list().setVisible(true);
        dispose();
        
    }//GEN-LAST:event_refresh_btnActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try{
					
					String newname;
					Statement st = conn.createStatement();
			       	        int n = st.executeUpdate("ALTER TABLE "+combobox.getSelectedItem()+" RENAME TO "+JOptionPane.showInputDialog("What should be the new name ?")+" ");
					JOptionPane.showMessageDialog(null, combobox.getSelectedItem()+"\n Month Name Is Changed");
                                        new member_and_meal_list().setVisible(true);
                                        dispose();
					
				}catch(Exception e1){
					JOptionPane.showMessageDialog(null, e1.getMessage()+"\n Please check You have Selected a month\n Or There is no month name exist that you have selected ");
				}
    }//GEN-LAST:event_jButton3ActionPerformed

    private void comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxActionPerformed
        
            try{
                String test=combobox.getSelectedItem().toString();
            if(test=="Select an item"){
               // table.setModel();
                //Datef.setText("");m1.setText("0");m2.setText("0");m3.setText("0");m4.setText("0");m5.setText("0");m6.setText("0");m7.setText("0");m8.setText("0");m9.setText("0");m10.setText("0");
            new member_and_meal_list().setVisible(true);
            dispose();
            }
            else{
                String query="select * from "+combobox.getSelectedItem()+" ";//from members_and_meals
					PreparedStatement pst = conn.prepareStatement(query);
					ResultSet rs = pst.executeQuery();
					
					table.setModel(DbUtils.resultSetToTableModel(rs));
					
					pst.close();
					rs.close();
            }
					
					
				}catch(Exception e){
					JOptionPane.showMessageDialog(null, e);
					
				}
        
    }//GEN-LAST:event_comboboxActionPerformed

    private void delete_monthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_monthActionPerformed

        if(combobox.getSelectedItem()=="Select an item"){
            JOptionPane.showMessageDialog(null, "You didn't select any month");
        }
        else{
            try {
            
            String newname;
					Statement st = conn.createStatement();
                                        int s=JOptionPane.showConfirmDialog(null, "Do you realy want to delete this month?","Delete",JOptionPane.YES_NO_CANCEL_OPTION);
                                        if(s==0){
                                           int n = st.executeUpdate("drop table "+combobox.getSelectedItem()+"");
					JOptionPane.showMessageDialog(null, "Deleted");
                                        new member_and_meal_list().setVisible(true);
                                        dispose(); 
                                        }
			       	        
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        }
    }//GEN-LAST:event_delete_monthActionPerformed

    public String name;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
					Statement st=conn.createStatement();
                                        name=JOptionPane.showInputDialog("Mongth Name ?");
					String a="CREATE TABLE "+name+" " +
                                           "(Date VARCHAR(225), " +
			                   " Aunshon INTEGER(225), " +
			                   " Parvez INTEGER(255), " + 
			                   " Jerry INTEGER(255), " + 
			                   " Kajol INTEGER(255), " + 
			                   " Sojib INTEGER(255), " + 
			                   " Robin INTEGER(255), " + 
			                   " Vai INTEGER(255), " + 
			                   " M8 INTEGER(255), " + 
			                   " M9 INTEGER(255), " +
                                           " M10 INTEGER(255)) " ;
                                        
					st.executeUpdate(a);
                                        st.close();
					JOptionPane.showMessageDialog(null, "New Mongth added");
                                        
				}
				catch(Exception e){
					JOptionPane.showMessageDialog(null, e.getMessage());
				}
        try{
					Statement st=conn.createStatement();
					String b="CREATE TABLE money_of_"+name+" " +
                                        "(mdate VARCHAR(255)," +  
                                        " mAunshon DOUBLE(255),"+
                                        " mParvez DOUBLE(255)," +
                                        " mJerry DOUBLE(255), " +
                                        " mKajol DOUBLE(255), " +
                                        " mSojib DOUBLE(255), " +
                                        " mRobin DOUBLE(255), " +
                                        " mVai DOUBLE(255), " +
                                        " mM8 DOUBLE(255)," +
                                        " mM9 DOUBLE(255), " +
                                        " mM10 DOUBLE(255), "  +
                                        " mspend DOUBLE(255)) ";
			                   
					st.executeUpdate(b);
					JOptionPane.showMessageDialog(null, "money box created");
                                        new member_and_meal_list().setVisible(true);
                                        dispose();
				}
				catch(Exception e){
					JOptionPane.showMessageDialog(null, e.getMessage());
				}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new add_meal().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new countpage().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        new Home().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(member_and_meal_list.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(member_and_meal_list.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(member_and_meal_list.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(member_and_meal_list.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new member_and_meal_list().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Home;
    private javax.swing.JComboBox<String> combobox;
    private javax.swing.JButton delete_month;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton refresh_btn;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
